[package]
name = "router"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "crates/*", "xtask"]

[dependencies]
server = { path = "crates/server" }
query-planner = { path = "crates/query-planner" }
execution = { path = "crates/execution" }
configuration = { path = "crates/configuration" }
tokio = { version = "1.10.0", features = ["full"] }
futures = { version = "0.3.15", features = ["thread-pool"]}
log = "0.4.14"
env_logger = "0.9.0"
structopt = "0.3.22"
directories = "3.0.2"

[dev-dependencies]
