[package]
name = "router"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "crates/*"]

[dependencies]
server = { path = "crates/server" }
query-planner = { path = "crates/query-planner" }
execution = { path = "crates/execution" }
configuration = { path = "crates/configuration" }
tokio = { version = "1.8.1", features = ["full"] }
futures = { version = "0.3.15", features = ["thread-pool"]}
log = "0.4.14"
env_logger = "0.8.4"
clap = "2.33.3"
serde_yaml = "0.8.17"

[dev-dependencies]
serde_json = "1.0.65"
maplit = "1.0.2"
