version: "3.9"
services:

  services:
    build: dockerfiles/federation-demo
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 4003:4003
      - 4004:4004
    command: npm run start
