version: '2.1'

jobs:
  build:
    parameters:
       cache_version:
        default: v1
        description: Cache version to use - increment this to build a fresh cache.
        type: string
    docker:
      - image: cimg/rust:1.52.1-node
    steps:
      - checkout
      - restore_cache:
            keys:
              - 'cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}'
      - run: cargo --version
      - run: cargo test --all
      - run: cargo fmt -- --check
      - run: cargo clippy --all --no-default-features -- -D warnings -D missing_docs -D future_incompatible -D missing_debug_implementations -D nonstandard_style -D future_incompatible -D unreachable_pub -D rust_2018_idioms
      - run: cargo build
      - save_cache:
            key: 'cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}'
            paths:
              - ~/.cargo
workflows:
  production:
    jobs:
      - build


