version: '2.1'

jobs:
  build:
    parameters:
      cache_version:
        default: v1
        description: Cache version to use - increment this to build a fresh cache.
        type: string
    docker:
      - image: cimg/rust:1.53.0-node
    steps:
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule sync --recursive; git submodule update --recursive --init
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - restore_cache:
          keys:
            - 'cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}'
      - run: cd submodules/supergraph-demo; docker-compose up -d; cd ../..
      - run: sudo npm install -g npm
      - run: sudo apt-get update
      - run: sudo apt-get install libssl-dev
      - run: cargo --version
      - run: cargo test --all
      - run: cargo fmt -- --check
      - run: cargo clippy --all --no-default-features -- -D warnings
      - run:
          name: Strict lint build
          command: cargo build --all-targets
          environment:
            RUSTFLAGS: -D warnings -D missing_docs -D future_incompatible -D missing_debug_implementations -D nonstandard_style -D future_incompatible -D unreachable_pub -D rust_2018_idioms
      - run: cargo rustdoc
      - save_cache:
          key: 'cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}'
          paths:
            - ~/.cargo

workflows:
  build:
    jobs:
      - build


