[package]
name = "configuration"
version = "0.1.0-prealpha.1"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.19"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.28"
maplit = "1.0.2"
typed-builder = "0.9.0"

[dev-dependencies]

