[package]
name = "configuration"
version = "0.1.0-prealpha.1"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

[features]
otlp-tonic = ["opentelemetry-otlp/tonic", "opentelemetry-otlp/tonic-build", "opentelemetry-otlp/prost", "tonic"]
otlp-grpcio = ["opentelemetry-otlp/grpc-sys", "opentelemetry-otlp/openssl"]
otlp-http = ["opentelemetry-otlp/http-proto"]
tls = ["opentelemetry-otlp/tls", "tonic/transport", "tonic/tls"]

[dependencies]
derivative = "2.2.0"
displaydoc = "0.2"
opentelemetry = { version = "0.16.0", features = ["serialize"] }
opentelemetry-otlp = { version = "0.9.0", default-features = false, features = ["serialize"], optional = true }
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.19"
thiserror = "1.0.29"
tonic = { version = "0.5.2", optional = true }
tracing = "0.1.26"
typed-builder = "0.9.0"
url = { version = "2.2.2", features = ["serde"] }

[dev-dependencies]
insta = "1.7.2"
