[package]
name = "query-planner"
version = "0.1.0-prealpha.1"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apollo-json-ext = { path = "../apollo-json-ext" }
harmonizer = { git = "https://github.com/apollographql/federation.git", rev = "34507803"}
parking_lot = "0.11"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
thiserror = "1.0.28"

[dev-dependencies]
insta = "1.7.2"
mockall = "0.10.2"
static_assertions = "1"
