[package]
name = "query-planner"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harmonizer = { git = "https://github.com/apollographql/federation.git", rev = "34507803"}
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
derive_more = "0.99.16"
thiserror = "1.0.26"


[dev-dependencies]
insta = "1.7.2"
mockall = "0.10.2"
