[package]
name = "query-planner"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harmonizer = { git = "https://github.com/apollographql/federation.git", branch = "query-planer-js-bridge"}
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
derive_more = "0.99.14"
thiserror = "1.0.25"


[dev-dependencies]
insta = "1.7.1"
mockall = "0.9.1"