[package]
name = "execution"
version = "0.1.0-prealpha.1"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apollo-json-ext = { path = "../apollo-json-ext" }
async-recursion = "0.3"
bytes = "1.1.0"
configuration = { path = "../configuration" }
derivative = "2.2.0"
derive_more = "0.99.16"
displaydoc = "0.2"
env_logger = "0.9.0"
futures = "0.3.16"
log = "0.4.14"
mockall = {version = "0.10.1", optional = true}
parking_lot = "0.11.1"
query-planner = { path = "../query-planner" }
reqwest = { version = "0.11.4", features = ["json", "stream"] }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.67"
serde_yaml = "0.8.19"
thiserror = "1.0.28"
tokio = { version = "1.11.0", features = ["full"] }
typed-builder = "0.9.0"

[dev-dependencies]
ctor = "0.1.20"
httpmock = "0.6.2"
maplit = "1.0.2"
static_assertions = "1"

[features]
mocks = ["mockall"]
