[package]
name = "execution"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
query-planner = { path = "../query-planner" }
configuration = { path = "../configuration" }
futures = "0.3.15"
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
derive_more = "0.99.14"
thiserror = "1.0.25"
reqwest = { version = "0.11.3", features = ["json", "stream"] }
tokio = { version = "1.6.2", features = ["full"] }
bytes = "1.0.1"
derivative = "2.2.0"
serde_yaml = "0.8.17"
log = "0.4.14"
env_logger = "0.8.4"
json-patch = "0.2.6"

[dev-dependencies]
httpmock = "0.5.8"
