[package]
name = "execution"
version = "0.1.0"
authors = ["bryncooke <bryncooke@gmail.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
query-planner = { path = "../query-planner" }
futures = "0.3.15"
serde_json = "1.0.64"
serde = "1.0.126"
derive_more = "0.99.14"
thiserror = "1.0.25"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }