[package]
name = "execution"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
query-planner = { path = "../query-planner" }
configuration = { path = "../configuration" }
futures = "0.3.16"
serde_json = "1.0.66"
serde = { version = "1.0.129", features = ["derive", "rc"] }
derive_more = "0.99.16"
thiserror = "1.0.26"
reqwest = { version = "0.11.4", features = ["json", "stream"] }
tokio = { version = "1.10.0", features = ["full"] }
bytes = "1.0.1"
derivative = "2.2.0"
serde_yaml = "0.8.19"
log = "0.4.14"
env_logger = "0.9.0"
parking_lot = "0.11.1"
typed-builder = "0.9.0"
mockall = {version = "0.10.1", optional = true}

[dev-dependencies]
httpmock = "0.6.2"
maplit = "1.0.2"
ctor = "0.1.20"

[features]
mocks = ["mockall"]
