version: '3'
services:
  router:
    container_name: router
    build: ./router
    environment:
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./supergraph.graphql:/etc/config/supergraph.graphql
    ports:
      - "127.0.0.1:4000:4000"
  products:
    container_name: products
    build: ./subgraphs/products
    ports:
      - "127.0.0.1:4001:4000"
  inventory:
    container_name: inventory
    build: ./subgraphs/inventory
    ports:
      - "127.0.0.1:4002:4000"
  users:
    container_name: users
    build: ./subgraphs/users
    ports:
      - "127.0.0.1:4003:4000"
