[package]
name = "server"
version = "0.1.0-prealpha.1"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

[features]
mocks = ["mockall"]
otlp = []

[dependencies]
configuration = { path = "../configuration" }
derivative = "2.2.0"
derive_more = "0.99.16"
execution = { path = "../execution" }
futures = { version = "0.3.15", features = ["thread-pool"] }
hotwatch = "0.4.5"
hyper = { version = "0.14.12", features = ["full"] }
log = "0.4.14"
mockall = {version = "0.10.1", optional = true}
once_cell = "1.8.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.15.0", features = ["collector_client", "rt-tokio"] }
parking_lot = "0.11.1"
query-planner = { path = "../query-planner" }
serde_json = "1.0.67"
serde_yaml = "0.8.19"
thiserror = "1.0.28"
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1.26"
tracing-opentelemetry = "0.15.0"
tracing-subscriber = "0.2.20"
typed-builder = "0.9.0"

[dev-dependencies]
ctor = "0.1.20"
env_logger = "0.9.0"
execution = { path = "../execution", features=["mocks"]}
reqwest = "0.11.4"
server = { path = ".", features=["mocks"]}
uuid = { version = "0.8.2", features = ["serde", "v4"] }
