[package]
name = "server"
version = "0.1.0"
authors = ["Apollo Graph, Inc. <opensource@apollographql.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.11", features = ["full"] }
tokio = { version = "1.8.1", features = ["full"] }
query-planner = { path = "../query-planner" }
execution = { path = "../execution" }
configuration = { path = "../configuration" }
futures = { version = "0.3.15", features = ["thread-pool"] }
typed-builder = "0.9.0"
derive_more = "0.99.16"
log = "0.4.14"
env_logger = "0.9.0"
hotwatch = "0.4.5"
thiserror = "1.0.26"
serde_json = "1.0.66"
derivative = "2.2.0"
serde_yaml = "0.8.17"
parking_lot = "0.11.1"
[dev-dependencies]
insta = "1.7.1"
mockall = "0.10.1"
reqwest = "0.11.4"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
ctor = "0.1.20"
